### ISSUE TITLE
Design Registration Page

### ISSUE THREAD

**Issue by imrvon** [zuri-training/price_compare_team_23#10]

**Comment by ibrahimadeyemi** [comment]
Desktop View: https://www.figma.com/file/qCgF6dPxQwS10dlcPjgOi8/Team-23-_-Price-Compare?node-id=435%3A1616
Mobile View: https://www.figma.com/file/qCgF6dPxQwS10dlcPjgOi8/Team-23-_-Price-Compare?node-id=1732%3A7895
