### ISSUE TITLE
Design Contact Page

### ISSUE THREAD

**Issue by imrvon** [zuri-training/price_compare_team_23#4]

**Comment by deinbofa** [comment]
assisted with User Research and flows.
I also finished the design for the contact page on Figma

**Comment by deinbofa** [comment]
![Contact Desktop](https://user-images.githubusercontent.com/54392522/183309804-625e3f08-049e-4de0-8b8e-348f4790245d.jpg)

**Comment by deinbofa** [comment]
![Contact mobile](https://user-images.githubusercontent.com/54392522/183309812-72a355f2-e423-4b49-bae3-09f0d408bacf.jpg)
