### ISSUE TITLE
Design Privacy Policy Page

### ISSUE THREAD

**Issue by imrvon** [zuri-training/price_compare_team_23#59]

**Comment by deinbofa** [comment]
Finished designing the 'Terms and Policies' and Privacy policy pages

**Comment by deinbofa** [comment]
![Terms and Policies](https://user-images.githubusercontent.com/54392522/183796314-6a6510b4-58d0-40fe-8640-e12347f4db07.jpg)
Terms and Policies page

**Comment by deinbofa** [comment]
![privacy policy](https://user-images.githubusercontent.com/54392522/183796509-e69795fa-370f-4681-a4c2-e545f5830ff7.jpg)
Privacy Policy page
